contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #scflowqc channel"
    url: https://nfcore.slack.com/channels/scflowqc
    about: Discussion about the nf-core/scflowqc pipeline
